### ISSUE TITLE
ERROR - TW FR

### ISSUE THREAD

**Issue by TBourgault** [cheesasaurus/twcheese#62]
Hi,
For some week, we can see an error :
[image](https://user-images.githubusercontent.com/19395507/68329434-7cca0280-00d1-11ea-9fb7-f20db4e9bafc.png)
"GET https://cheesasaurus.github.io/twcheese/launch/ASS.js?5243557 net::ERR_BLOCKED_BY_CLIENT
send @ game.js:11
ajax @ game.js:11
eval @ VM1005:3
(anonymous) @ game.js:9
globalEval @ game.js:9
runEntry @ game.js:160
openEntry @ game.js:160
(anonymous) @ game.js:160
dispatch @ game.js:9
v.handle @ game.js:9"
In my console. 
I don't see were the problem is...

**Comment by cheesasaurus** [comment]
net::ERR_BLOCKED_BY_CLIENT means your browser blocked it from loading. Try fiddling with your adblocker (I promise there's no advertisements)

**Comment by TBourgault** [comment]
Was that, i'm using ghostery and I have to disable it totally... strange thing but now it's ok ;)

Thank you
