### ISSUE TITLE
months not parsed correctly: br

### ISSUE THREAD

**Issue by cheesasaurus** [cheesasaurus/twcheese#67]
see Natan's comment here:
https://github.com/cheesasaurus/twcheese/commit/d3ba83866c7ab5842e5aa885738d3b3fb00d97d1#commitcomment-39549703

**Comment by cheesasaurus** [comment]
@natanprog 
I believe this should be fixed now (made an account on br and tested myself).

**Comment by natanprog** [comment]
@cheesasaurus 

The script works fine on the .BR server now

**Thanks!**
